general {
  hide_cursor = false
  ignore_empty_input = true
  immediate_render = true
}

auth {
  pam {
    enabled = true
  }

  fingerprint {
    enabled = true
    ready_message = Scan fingerprint to unlock
    present_message = Scanning...
    retry_delay = 250
  }
}

animations {
  enabled = true
}

background {
  monitor = eDP-1
  path = ~/.config/hypr/cc.png
  blur_passes = 1
  blur_size = 1
  vibrancy = 0.25
  vibrancy_darkness = 1.1
}

label {
  monitor =
  text = $TIME
  font_size = 90
  font_family = Adwaita Sans Bold
  color = rgba(255, 255, 255, 0.7)
  position = 70, 70
  halign = left
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +'%A, %d %B %Y')"
  font_size = 24
  font_family = Adwaita Sans Bold
  color = rgba(255, 255, 255, 0.7)
  position = 70, -10
  halign = left
  valign = center
}

input_field {
  monitor =

  size = 340, 50
  position = 70, -120
  halign = left
  valign = center
  
  outline_thickness = 2
  rounding = 16
  
  outer_color = rgba(255, 255, 255, 0.18)
  inner_color = rgba(0, 0, 0, 0, 0.25)

  font_color = rgb(255, 255, 255)

  placeholder_text = Password
  placeholder_text_color = rgba(255, 255, 255, 0.35)

  fail_text = Incorrect password
  fail_transition = 1

  check_color = rgb(90, 170, 255)
  fail_color = rgb(255, 80, 80)
  capslock_color = rgb(255, 200, 60)

  dots_center = true
  dots_spacing = 0.25
}
