general {
  hide_cursor = false
  ignore_empty_input = true
}

animations {
  enabled = true
}

background {
  monitor = eDP-1
  path = ~/dotfiles/hypr/cc.png
  blur_passes = 1
  blur_size = 1
  vibrancy = 0.25
  vibrancy_darkness = 1.1
}

label {
  monitor = eDP-1
  text = $TIME
  font_size = 90
  font_family = Adwaita Sans Bold
  color = rgba(255, 255, 255, 0.7)
  position = 0, 0
  halign = left
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +'%A, %d %B %Y')"
  font_size = 28
  font_family = Adwaita Sans Bold
  color = rgba(255, 255, 255, 0.7)
  position = 0, -90
  halign = left
  valign = center
}
